### ISSUE TITLE
Deprecated Api keys?

### ISSUE THREAD

**Issue by vojkny** [Sybit-Education/airtable.java#81]
Can you add in documentation how this can be used with API tokens?

**Comment by stritti** [comment]
Just use it same way than user token.

**Comment by jaydengregit** [comment]
I am trying to use from jitpack the below version.

		<dependency>
			<groupId>com.github.Sybit-Education</groupId>
			<artifactId>airtable.java</artifactId>
			<version>0.2.2</version>
		</dependency>
		
I am passing my API token instead of API Key like below

airtable = new Airtable().configure("MyUserToken");

I double checked and passing the correct BaseID

Base base = airtable.base("MyBaseID");

However it fails always with NOT_FOUND

So do we need to do anything else to make it work with user token instead of API KEY?

**Comment by stritti** [comment]
Hi @jaydengregit,
it should normally be enough if you pass the API key instead of user key. Probably you have a typo in the table name? My fault often is to forget the case sensitivity: If your Table has the name "TestTable" within Airtable you have to refer also in the API using "TestTable".

**Comment by stritti** [comment]
With release 0.3.0 the api key is marked deprecated an personal access token is added.
